name: "CI"
on:
  push:
    branches:
      - devel
  pull_request:
    branches:
      - devel
  schedule:
    - cron: '0 0 * * *'
  workflow_dispatch:
env:
  HUGEPAGES: 256

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          submodules: recursive

      - name: Build container images
        run: make build

      - name: Setup huge-pages
        run: make setup HUGEPAGES=$HUGEPAGES

      - name: Start containers
        run: |
          make up OPTS=--detach || (make logs OPTS=''; exit 1)

      - name: Wait for the Gateway to be listening
        timeout-minutes: 1
        run: |
          . .env
          until nc -z localhost $NVMEOF_GW_PORT; do
            echo -n .
            sleep 1
          done
          echo

      - name: List containers
        run: make ps

      - name: List processes
        run: make top

      - name: Print hosts
        run: make run SVC=nvmeof-cli OPTS=--entrypoint=bash CMD='-c "cat /etc/hosts"'

      - name: Print DNS config
        run: make run SVC=nvmeof-cli OPTS=--entrypoint=bash CMD='-c "cat /etc/resolv.conf"'

      - name: Run test
        run: . .env && make demo SERVER_ADDRESS=$NVMEOF_IP_ADDRESS OPTS=-T # Disable TTY

      #- name: Setup tmate session
      #  uses: mxschmitt/action-tmate@v3
      #  with:
      #    limit-access-to-actor: true

      - name: Display logs
        run: make logs OPTS=''

      - name: Shut containers down
        run: make down

      - name: Clean up environment
        run: make clean
